# Generated by Django 4.2.7 on 2023-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
